name: Deploy Vite React & Go Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy and Build on VM
        run: |
          ssh ${{ secrets.VM_USER_NAME }}@${{ secrets.VM_HOST }} << 'EOF'
            set -e  # Exit on error

            echo "Pulling latest changes..."
            cd ~/myWebSite/KarthikShenoy.in/
            git pull origin main

            # Build Vite React App
            echo "Building Vite React App..."
            cd ~/myWebSite/KarthikShenoy.in/client/
            npm install
            npm run build

            # Copy dist to /var/www/dist_root
            echo "Copying dist to /var/www/dist_root..."
            sudo cp -r ~/myWebSite/KarthikShenoy.in/client/dist/* /var/www/dist_root
            
            # Build and Run Go Backend
            echo "Building Go Backend..."
            cd ~/myWebSite/KarthikShenoy.in/server
            go mod tidy
            go build -o server main.go
            chmod +x server
            sudo kill -9 $(sudo lsof -t -i:3000) || true  # Kill existing process if running
            nohup ./main > nohup.out 2>&1 &  # Run in background

            # Restart Nginx
            echo "Restarting Nginx..."
            sudo systemctl restart nginx

            echo "Deployment complete!"
          EOF
